[toolchain]
anchor_version = "0.32.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
daily_draw = "gvd3fv3QgWvTMzLfxN2HBKkspAeVwzGBCZkW9ixaucM"

[programs.localnet]
daily_draw = "gvd3fv3QgWvTMzLfxN2HBKkspAeVwzGBCZkW9ixaucM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'integration tests run against devnet: see scripts/'"
